name: LottoPools
favicon: null
layout_spectrum: 0.8726090341806412
typography_spectrum: 0.2840524099301547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5493168232496828
  lightness: 0.7378948759287596
  saturation: 0.5170252569951117
  rhythmicContrast: 0.5943385045975447
purpose: []
